services:
  vscode:
    image: vscode-slim-image 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: RUL_forecasting
    ports:
      - "3000:3000"  
      - "8000:8000"  
    volumes:
      - .:/home/workspace
    environment:
      - PASSWORD=1  
    networks:
      - my_network 
    restart: always
    profiles:
      - build_enabled 

networks:
  my_network:
    driver: bridge  

