target:
- 'y'
continuous_cols:
- y_lag_1
- y_lag_2
- y_lag_3
- y_lag_4
- y_lag_5
- y_lag_240
- y_lag_241
- y_lag_242
- y_lag_243
- y_lag_244
- y_lag_5760
- y_lag_5761
- y_lag_5762
- y_lag_5763
- y_lag_5764
- y_rolling_3_mean
- y_rolling_3_std
- y_rolling_6_mean
- y_rolling_6_std
- y_rolling_12_mean
- y_rolling_12_std
- y_rolling_48_mean
- y_rolling_48_std
- y_5760_seasonal_rolling_3_mean
- y_5760_seasonal_rolling_3_std
- y_40320_seasonal_rolling_3_mean
- y_40320_seasonal_rolling_3_std
- y_ewma_span_40320
- y_ewma_span_5760
- y_ewma_span_240
- ds_Elapsed
- ds_Month_sin_1
- ds_Month_sin_2
- ds_Month_sin_3
- ds_Month_sin_4
- ds_Month_sin_5
- ds_Month_cos_1
- ds_Month_cos_2
- ds_Month_cos_3
- ds_Month_cos_4
- ds_Month_cos_5
- ds_Hour_sin_1
- ds_Hour_sin_2
- ds_Hour_sin_3
- ds_Hour_sin_4
- ds_Hour_sin_5
- ds_Hour_cos_1
- ds_Hour_cos_2
- ds_Hour_cos_3
- ds_Hour_cos_4
- ds_Hour_cos_5
- ds_Minute_sin_1
- ds_Minute_sin_2
categorical_cols:
- ds_Month
- ds_Quarter
- ds_Day
- ds_Dayofweek
- ds_Dayofyear
- ds_Hour
- ds_Minute
- ds_Second
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
task: regression
head: LinearHead
head_config:
  layers: '32'
  activation: ReLU
  dropout: 0.0
  use_batch_norm: false
  initialization: kaiming
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: MSELoss
metrics:
- mean_squared_error
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.ft_transformer
_model_name: FTTransformerModel
_backbone_name: FTTransformerBackbone
_config_name: FTTransformerConfig
input_embed_dim: 32
embedding_initialization: kaiming_uniform
embedding_bias: true
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
attn_feature_importance: true
num_heads: 4
num_attn_blocks: 3
transformer_head_dim: 64
attn_dropout: 0.2
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 1024
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 1000
min_epochs: 1
max_time: null
accelerator: auto
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 8
enable_checkpointing: true
